version: "3.8"

services:
  lubelogger:
    container_name: lubelogger
    image: ghcr.io/hargata/lubelogger:v1.3.4
    restart: unless-stopped
    environment:
      #- POSTGRES_CONNECTION="Host=lubelogger-postgres;Username=lubelogger;Password=${POSTGRES_PASSWORD};Database=lubelogger;"
      - LC_ALL=${LC_ALL}
      - LANG=${LC_ALL}
      - LOGGING__LOGLEVEL__DEFAULT=Error
    volumes:
      - ${APP_DATA_DIR}/data/lubelogger/config:/App/config
      - ${APP_DATA_DIR}/data/lubelogger/data:/App/data
      - ${APP_DATA_DIR}/data/lubelogger/translations:/App/wwwroot/translations
      - ${APP_DATA_DIR}/data/lubelogger/documents:/App/wwwroot/documents
      - ${APP_DATA_DIR}/data/lubelogger/images:/App/wwwroot/images
      - ${APP_DATA_DIR}/data/lubelogger/temp:/App/wwwroot/temp
      - ${APP_DATA_DIR}/data/lubelogger/log:/App/log
      - ${APP_DATA_DIR}/data/lubelogger/keys:/root/.aspnet/DataProtection-Keys
    ports:
      - ${APP_PORT}:8080
    # depends_on:
    #   - lubelogger-postgres
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true


  # lubelogger-postgres:
  #   container_name: lubelogger-postgres
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=lubelogger
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=lubelogger
  #   volumes:
  #     - ${APP_DATA_DIR}/db:/var/lib/postgresql/data
  #   networks:
  #     - tipi_main_network
  #   healthcheck:
  #     test: ["CMD", "pg_isready"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5